# Generated by Django 6.0.5 on 2026-05-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_oderitem_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
